---
- name: "Manage Clusters"
  hosts: "{{ target_clusters }}"
  connection: local
  gather_facts: false

  pre_tasks:
    - name: "Check labels on the managedcluster"
      k8s_info:
        api_version: cluster.open-cluster-management.io/v1
        kind: ManagedCluster
        name: "{{ inventory_hostname }}"
      register: check_mc_label

    - name: Set run for cluster variable
      set_fact:
        mc_run_playbook: "{{ 'ztp-ansible' not in check_mc_label.resources[0].metadata.labels }}"

    - debug:
        msg: "{{ mc_run_playbook }}"

    - name: "Create maintenance label in managed clusters"
      k8s:
        state: patched
        api_version: cluster.open-cluster-management.io/v1
        kind: ManagedCluster
        name: "{{ inventory_hostname }}"
        definition:
          metadata:
            labels:
              ztp-ansible: "running"
      when: mc_run_playbook
      register: maintenance_label_set

  tasks:
    - name: Pause for 10 minutes
      wait_for:
        timeout: 600
      when: mc_run_playbook

#    - name: "This is just a placeholder for a sample role"
#      include_role:
#        name: ../roles/cool-vz-role-goes-here
#      vars:
#        custom_var_1: "{{ custom_var_1 }}"
#        custom_var_2: "{{ custom_var_2 }}"
#      when: maintenance_label_set is changed

  post_tasks:
    - name: "Create ZTP handled label in target_clusters"
      k8s:
        state: patched
        api_version: cluster.open-cluster-management.io/v1
        kind: ManagedCluster
        name: "{{ inventory_hostname }}"
        definition:
          metadata:
            labels:
              ztp-ansible: "completed"
      when:
      - mc_run_playbook
      - maintenance_label_set is changed
